on:
  workflow_dispatch:
    inputs:
      start_urls:
        description: "開始URL（カンマ区切り可）"
        required: true
      devices:
        description: "デバイス/解像度（例: 'Desktop 1440x900,iPhone 13,375x812'）"
        required: false
        default: "Desktop 1440x900,iPhone 13"
      full_page:
        description: "フルページ（true/false）"
        required: false
        default: "true"
      # ↓ 追加
      same_host_only:
        description: "同一ホストのみ巡回（true/false）"
        required: false
        default: "true"
      path_prefix_mode:
        description: "開始URLのパス配下のみ: start / 制限なし: none"
        required: false
        default: "start"
      max_depth:
        description: "最大深さ（0=開始ページのみ）"
        required: false
        default: "2"
      max_pages:
        description: "最大ページ数（総数のブレーキ）"
        required: false
        default: "300"
      scale:
        description: "解像度スケール（1=等倍, 2=2倍）"
        required: false
        default: "2"
      wait_between_ms:
        description: "撮影間隔ms（ブロック回避用）"
        required: false
        default: "200"
