name: Capture & Publish (simple)

on:
  workflow_dispatch:
    inputs:
      start_urls:
        description: "開始URL（カンマ区切り可）"
        required: true
      devices:
        description: "デバイス/解像度（例: 'Desktop 1440x900,iPhone 13,375x812'）"
        required: false
        default: "Desktop 1440x900,iPhone 13"
      full_page:
        description: "フルページ（true/false）"
        required: false
        default: "true"
      same_host_only:
        description: "同一ホストのみ巡回（true/false）"
        required: false
        default: "true"
      path_prefix_mode:
        description: "開始URLのパス配下のみ: start / 制限なし: none"
        required: false
        default: "start"
      max_depth:
        description: "最大深さ（0=開始ページのみ）"
        required: false
        default: "2"
      max_pages:
        description: "最大ページ数（総数のブレーキ）"
        required: false
        default: "300"
      filename_mode:
        description: "ファイル名モード: flat=フラット / tree=ディレクトリ構造保持"
        required: false
        default: "flat"
      scale:
        description: "解像度スケール（1=等倍, 2=2倍, 3=3倍）"
        required: false
        default: "2"
      wait_between_ms:
        description: "撮影間隔ms（ブロック回避用）"
        required: false
        default: "200"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm install --no-audit --no-fund
          npx playwright install --with-deps

      - name: Capture screenshots
        run: npm run capture
        env:
          START_URLS: ${{ inputs.start_urls }}
          DEVICES: ${{ inputs.devices }}
          FULL_PAGE: ${{ inputs.full_page }}
          SAME_HOST_ONLY: ${{ inputs.same_host_only }}
          PATH_PREFIX_MODE: ${{ inputs.path_prefix_mode }}
          MAX_DEPTH: ${{ inputs.max_depth }}
          MAX_PAGES: ${{ inputs.max_pages }}
          SCALE: ${{ inputs.scale }}
          FILENAME_MODE: ${{ inputs.filename_mode }}
          WAIT_BETWEEN_MS: ${{ inputs.wait_between_ms }}
          OUT_DIR: public

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: run
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
