name: Capture & Publish (simple)

on:
  workflow_dispatch:
    inputs:
      start_urls:
        description: "開始URL（カンマ区切り可）"
        required: true
      devices:
        description: "デバイス/解像度（例: 'Desktop 1440x900,iPhone 13,375x812'）"
        required: false
        default: "Desktop 1440x900,iPhone 13"
      full_page:
        description: "フルページ（true/false）"
        required: false
        default: "true"
      max_depth:
        description: "最大深さ（0=開始ページのみ）"
        required: false
        default: "0"
      max_pages:
        description: "最大ページ数"
        required: false
        default: "50"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Install deps
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Capture screenshots
        run: npm run capture
        env:
          START_URLS: ${{ inputs.start_urls }}
          DEVICES: ${{ inputs.devices }}
          FULL_PAGE: ${{ inputs.full_page }}
          MAX_DEPTH: ${{ inputs.max_depth }}
          MAX_PAGES: ${{ inputs.max_pages }}
          OUT_DIR: public

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: run
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        
